version: '2'

labels:

    rocks.puffin.name: Flarum
    rocks.puffin.subtitle: forums made simple
    rocks.puffin.website: http://flarum.org
    rocks.puffin.description: |
        Flarum is the next-generation forum software that makes online discussion fun. 
        It's simple, fast, and free. 
        Administrator username is 'admin' and password is 'password'.

services:
 
    main:
        image: loomchild/flarum
        depends_on:
            - db
        ports: 
            - 80
        volumes: 
            - main_data:/var/www/html
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=80
        networks:
            - front
            - back
            - default

    db:
        image: loomchild/mariadb
        ports: 
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: flarum
            MYSQL_USER: flarum
            MYSQL_PASSWORD: flarum
        volumes: 
            - db_data:/var/lib/mysql

volumes:
    main_data:
    db_data:

networks:
    front:
        external:
            name: "puffin_front"
    back:
        external:
            name: "puffin_back"
